name: aitoy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  http: ^1.2.1
  audioplayers: ^6.0.0
  path_provider: ^2.1.3
  porcupine_flutter: ^3.0.3
  permission_handler: ^11.3.1
  speech_to_text: ^6.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/keywords/Hey-Rodney_en_android_v3_0_0.ppn